### ISSUE TITLE
Label Ids ad-event-listeners/js

### ISSUE THREAD

**Issue by SamiBeig** [googleads/google-publisher-tag-samples#106]
* If not pre-filled, update the title of this issue with the name of the audit this feedback pertains to.
* Provide details of any issues with the documentation or improvements you'd like to see below.

Provide more support on how to pass label ids to the slotRenderEnded() event listener. Is there any specific configuration that needs to be applied to the label id itself in GAM for it to be visible via the event listener? The example also doesn't include a label ID being passed in the details message.

**Comment by jimper** [comment]
Hi @SamiBeig, thanks for the report. Support for the `labelIds` field was actually removed way back on Aug 20, 2018 :

> **Removing the labelIds field in Google Publisher Tag (GPT)**
> As of August 20, 2018, we've deactivated and removed the labelIds field, part of the SlotRenderEndedEvent object in the Google Publisher Tag. This is a legacy field that had historically been used in conjunction with [competitive exclusions](https://support.google.com/admanager/answer/6145371), but it's been deprecated since July 2017. You should notice no impact to ad serving.

(source: [Ad Manager release notes](https://support.google.com/admanager/answer/7636572))

Unfortunately, while the logic to populate the field was removed, the field itself was accidentally left in the API. As of this week, the field is now properly marked `@deprecated`, and there are plans to remove it fully in early 2025.
