### ISSUE TITLE
Sample feedback: integrations/react

### ISSUE THREAD

**Issue by QuinnVSD** [googleads/google-publisher-tag-samples#107]
The sample project will not load in the embed, with the following error:

"Looks like this project is being embedded without proper isolation headers."

**Comment by jimper** [comment]
Hi @QuinnVSD, what browser are you using? Looking at the linked docs it seems like this is unfortunately expected behavior in non-Chromium browsers. If that's indeed the issue, it seems like visiting the sample directly at https://stackblitz.com/edit/gpt-react should work.
