### ISSUE TITLE
Can't get web interstitial ad to work on Nextjs

### ISSUE THREAD

**Issue by Iliyass** [googleads/google-publisher-tag-samples#17]
I have created a repo with a sample nextjs app to reproduce this issue, I have copied the sample from this repo, and the slot doesn't load.

https://github.com/Iliyass/nextjs-web-interstitial-ad

Thanks.

**Comment by jimper** [comment]
I'm not familiar with Nextjs, but I assume https://github.com/Iliyass/nextjs-web-interstitial-ad/blob/master/pages/index.js is the code responsible for loading the interstitial ad? If so, I see two issues:

1. At [line 42](https://github.com/Iliyass/nextjs-web-interstitial-ad/blob/master/pages/index.js#L42) you're defining a static slot that doesn't have a corresponding div in the body of the page.
2. Without the static slot div, there's no call to googletag.display(), which means no ad request is being made (see [line 96](https://github.com/googleads/google-publisher-tag-samples/blob/main/basic/display-web-interstitial-ad/demo.html#L96) in our example).

So you can either add the static slot div to mimic our example, or remove the definition of that slot and instead call googletag.display(interstitialSlot); directly after the call to googletag.enableServices();.

**Comment by Iliyass** [comment]
Thank you so much @jimper.
I wasn't calling the display function, the interstitial is working great now.
