### ISSUE TITLE
请问一下 web 原生广告如何做？

### ISSUE THREAD

**Issue by haijee** [googleads/google-publisher-tag-samples#18]
我要在 Vue 中使用，谢谢

**Comment by jimper** [comment]
Hi @haijee, it looks like you're asking about [native ads](https://support.google.com/admanager/answer/6366845). To display native ads using GPT, you need to use the [`fluid`](https://developers.google.com/publisher-tag/reference#googletag.NamedSize) size. There's info about working with the fluid size in our [Ad sizes guide](https://developers.google.com/publisher-tag/guides/ad-sizes#fluid_ads).

**Comment by haijee** [comment]
我有一个  原生ID  但是我不知道这个原生ID是如何使用的，请问能给我看下代码示例吗  
我不太理解文档

**Comment by jimper** [comment]
See https://jsfiddle.net/6u3Lvhjz/ for a working example.

**Comment by haijee** [comment]
const adPath = `/${AdUnit}/${parentUnit}/${childUnit}`
  googletag.cmd.push(function () {
         const targetSlot = googletag.defineSlot(adPath, ['fluid'], divid).addService(googletag.pubads())
        googletag.enableServices()
        googletag.display(divid)
    })
我这样写 但是不能显示
我有四个参数
native id （我不知道这个ID是怎么使用）例如 1871910
AdUnit  id  例如 31777719103
parentUnit 
childUnit

这是我的微信 haijee

**Comment by jimper** [comment]
I'm not sure what the IDs you've provided are. The correct format for adPath should be:

/`network-code`/`parent-unit-code`/.../`ad-unit-code`

`network-code` = a [unique ID for the AdManager network](https://support.google.com/admanager/answer/7674889#network-code) that owns the ad unit
`parent-unit-code`(s) = parents of the ad unit to be displayed
`ad-unit-code` = the ad unit to be  displayed

You may need to work with an admin for your AdManager network for identify the correct values to use. You could also try having AdManager [auto-generate tags](https://support.google.com/admanager/answer/177207) for you.

**Comment by haijee** [comment]
谢谢
我看 AdManager 后台 没有提示说可以生成代码，我在看一下吧

还有一个问题 就是我的广告都是在当前标签页打开的，但是我的需求在 浏览器新的标签页面打开

**Comment by jimper** [comment]
There's a setting for that in AdManager: https://support.google.com/admanager/answer/191228.

If you need help configuring that or using the tag generator, click "Contact Us" at the link above to reach out to AdManager support.
