### ISSUE TITLE
Issue with loading status: basic/display-web-interstitial-ad

### ISSUE THREAD

**Issue by html5maker** [googleads/google-publisher-tag-samples#20]
On the demo page on first load it's showing the "Interstitial is loaded." and "TRIGGER INTERSTITIAL" link.
But after clicking the trigger interstitial link and reloading the page it is stuck on "Interstitial is loading..."

**Comment by jimper** [comment]
Interstitials have a fixed frequency cap that prevents displaying an ad to the same user more than once per hour, per subdomain. This restriction is documented in the [Ad Manager help center](https://support.google.com/admanager/answer/9840201). I'll make sure the sample docs have a note about this as well.

As mentioned in [this comment](https://github.com/googleads/google-publisher-tag-samples/blob/main/basic/display-web-interstitial-ad/demo.html#L43), you can clear local storage in your browser to side step this restriction while testing. Documentation on modifying local storage in Chrome can be [found here](https://developer.chrome.com/docs/devtools/storage/localstorage/).
