### ISSUE TITLE
Safe frame: basic/display-web-interstitial-ad

### ISSUE THREAD

**Issue by html5maker** [googleads/google-publisher-tag-samples#21]
Is there a way to make this work with a Safe Frame (sandboxed) option enabled for the ad?

**Comment by jimper** [comment]
As long as the ad is configured to render in a SafeFrame (either in the Ad Manager UI or via GPT's page/slot level settings), it should just work. I ran a quick test where I modified the sample to use [GPTs page-level setting](https://developers.google.com/publisher-tag/reference#googletag.PubAdsService_setForceSafeFrame) to force SafeFrame for all ads and the interstitial ad seemed to render in a sandboxed iframe as expected.

Is there some specific scenario where you're not able to get this working?

**Comment by html5maker** [comment]
So the problem with interstitial ad and Safe frame is that by default the safe frame api will set the interstitial container css to postion:absolute.
It could look fine at first glance but if you will add more content and scroll the page - it will not work.
Is there a way to set the safeframe container position to css FIXED?

**Comment by jimper** [comment]
Is there a sample page where I can observe the issue you're seeing? Or can you provide more specific steps for me to reproduce it on my own?

**Comment by html5maker** [comment]
Here is the page with interstitial banner inside a safeframe:
[https://cdn.logotypemaker.com/demo/safeframe.html](https://cdn.logotypemaker.com/demo/safeframe.html)

The macros that I've used for Google Ad Manager creative (custom code option with out-of-page size):

```
<script src="https://developmentstorage.bannernow.com/adv/ckpljjraf000q5axadohakod3/embed.js?responsive=0&bnTag=%%CLICK_URL_ESC%%%%DEST_URL_ESC_ESC%%&cb=%%CACHEBUSTER%%&impressionpixel=%%VIEW_URL_ESC%%" async></script>
```

[safeframe-example.zip](https://github.com/googleads/google-publisher-tag-samples/files/6623977/safeframe-example.zip)

The embed.js is using safeframe api to expand/collapse safe frame. 
If you will try to scroll the page - safe frame api will return 0 as expansion value and the interstitial will fail to expand.

<img width="689" alt="google-ad-manager" src="https://user-images.githubusercontent.com/27346151/121361785-e3f70b00-c935-11eb-9593-da9120873491.png">

**Comment by html5maker** [comment]
Here is a better example:

This script should load and display google interstitial sample on page load:
```
<script>
    window.googletag = window.googletag || {cmd: []};

    var interstitialSlot;

    googletag.cmd.push(function() {
       googletag.pubads().setForceSafeFrame(true);

      interstitialSlot = googletag.defineOutOfPageSlot('/6355419/Travel/Europe/France/Paris', googletag.enums.OutOfPageFormat.INTERSTITIAL);
      if (interstitialSlot) {
        interstitialSlot.addService(googletag.pubads());
      }
      googletag.pubads().enableSingleRequest();
      googletag.enableServices();
      googletag.display(interstitialSlot);
    });
  </script>
```

And this one - a custom interstitial slot from my google ad manager:
```
  <script>
    window.googletag = window.googletag || {cmd: []};

    var interstitialSlot;

    googletag.cmd.push(function() {
       googletag.pubads().setForceSafeFrame(true);

      interstitialSlot = googletag.defineOutOfPageSlot('/22080696972/safe-frame-test-ad-unit', googletag.enums.OutOfPageFormat.INTERSTITIAL);
      if (interstitialSlot) {
        interstitialSlot.addService(googletag.pubads());
      }
      googletag.pubads().enableSingleRequest();
      googletag.enableServices();
      googletag.display(interstitialSlot);
    });
  </script>
```

Because it's an interstitial overlay format I expect that the custom ad will have css position set to FIXED

**Comment by jimper** [comment]
Thanks for the detailed examples. It looks like the problem you're encountering is an interaction between a **custom** out-of-page creative and the SafeFrame API.

Just to be clear, the sample code in this repo is for [GPT-managed web interstitials](https://support.google.com/admanager/answer/9840201). These only support specific sizes (320x480, 300x250, or 336x280) and can only be displayed between page views. As far as I can tell they work as expected with SafeFrame enabled, even when adding/removing content and scrolling the page.

I suspect it may not be possible to use SafeFrame with your completely custom interstitial implementation. However, I'm not especially knowledgable about custom creatives, so you should follow up on the [Ad Manager Community forum](https://support.google.com/admanager/thread/new) if switching to GPT-managed interstitials isn't an option. The specialists there should be able to give you a more definitive answer.
