### ISSUE TITLE
Key:value targeting for Audience Segments

### ISSUE THREAD

**Issue by html5maker** [googleads/google-publisher-tag-samples#22]
In Google Ad Manager 360 I am collecting first-party audience segments and I want to pass the **segment id** (numeric value) into the banner.

For example: 
```
googletag
    .defineSlot('/6355419/Travel/Europe/France/Paris', [300, 250], 'banner1')
    .addService(googletag.pubads())
    .setTargeting('segment') //here I want to automatically pass the segment id from first party Google Ad Manager
```

Is there any way to do this using key:value targeting ( [https://developers.google.com/publisher-tag/guides/key-value-targeting](https://developers.google.com/publisher-tag/guides/key-value-targeting) )?  

Thanks in advance

**Comment by jimper** [comment]
What are you trying to achieve with this? As far as I'm aware it's not possible to directly target an audience segment. Rather, you can specify custom key-values when you create a segment. Those custom key-values are then used as a signal to determine whether a user is eligible to be included in the segment. See [this help center article](https://support.google.com/admanager/answer/2423438) for details.

**Comment by html5maker** [comment]
I'm trying to create the html5 ad that will show different content to different segments.
Since I have more than 200 segments I don't want to create 200 ads (one banner for each segment) and rather have one banner that will have if else logic for each segment and for this I need to pass the segment id from outside of the banner.
So basically if I want to show different banners to different segments - right now I need to create 200+ banners for each size multiplied by number of campaigns (which is an insane number).

**Comment by jimper** [comment]
GPT itself doesn't know the audience a specific user is in and there's no special support for passing in segment IDs (as far as I know), so you'd need to define a custom key-value and provide the ID yourself somehow. At that point, you're really just describing normal key-value targeting, which can be accomplished as described in the [guide linked earlier](https://developers.google.com/publisher-tag/guides/key-value-targeting).

That said, you may want to take a step back here and determine if there's a better way to structure your inventory on the Ad Manager side to accomplish what you're trying to do. I recommend either reaching out on the [Ad Manager community forum](https://support.google.com/admanager/thread/new) or contacting the technical account manager for your Ad Manager account for assistance.
