### ISSUE TITLE
Demo not work load URL failed

### ISSUE THREAD

**Issue by osteamhcm** [googleads/google-publisher-tag-samples#23]
Demo not work load URL failed

**Comment by jimper** [comment]
Hey there, what sample is this in reference to? Please also clarify what the problem was. Were you unable to access the demo page itself, or was there an issue loading an ad on the demo page?

**Comment by jimper** [comment]
Closing this for now due to a lack of info. If you're still running into problems running any of the samples, feel free to reopen this issue or create a new one with additional details.
