### ISSUE TITLE
How to call LazzyLoad in separated slots?

### ISSUE THREAD

**Issue by luciano2000** [googleads/google-publisher-tag-samples#24]
How can I define slots only when page is scrolled ?

Here in your example we have a problem 
https://googleads.github.io/google-publisher-tag-samples/advanced/lazy-loading/demo.html?dfpdeb 

![lazzyload](https://user-images.githubusercontent.com/82453/128202912-dfa776a1-95a6-4193-9d8f-f1934df405fd.png)

But, in Globo.com the LazzyLoad works fine. (2 slots on begin, 3 and 4 later)
https://globo.com/?dfpdeb

**Comment by jimper** [comment]
Hey @luciano2000, the message in the pub console is a warning, not an error. Warnings are meant to let you know that something *might* be incorrect or misconfigured, but they aren't necessarily indicative of a problem that needs to be fixed. If you scroll the demo page down to the point where Ad Slot 3 is fetched you'll see the warning goes away.

So, what you're seeing on the demo page is the GPT lazy loading implementation working the way it's designed to. It seems the other page you linked to (globo.com) has it's own custom lazy loading implementation.
