### ISSUE TITLE
Sample feedback: basic/display-web-interstitial-ad

### ISSUE THREAD

**Issue by JunItoMixi** [googleads/google-publisher-tag-samples#28]
https://developers.google.com/publisher-tag/samples/display-web-interstitial-ad
I have a question about the above sample code

All <a> tags in this sample code
data-google-interstitial is "true".

But I want to make only certain links interstitial.

How should it be implemented?

**Comment by jimper** [comment]
Hi @JunItoMixi!

By default web interstitials apply to all eligible links on the page. You can prevent a link from triggering an interstitial by specifying a `data-google-interstitial="false"` attribute either on the anchor element itself or any parent element of the anchor, as shown around [line 87 in the sample code](https://github.com/googleads/google-publisher-tag-samples/blob/main/basic/display-web-interstitial-ad/demo.html#L87).

**Comment by JunItoMixi** [comment]
I decided to set data-google-interstitial = "false" for all a tags.
And when it ignited, I decided to remove only the designated place.
Thank you!
