### ISSUE TITLE
Sample feedback: advanced/infinite-content

### ISSUE THREAD

**Issue by michelangelo246** [googleads/google-publisher-tag-samples#35]
* If not pre-filled, update the title of this issue with the name of the audit this feedback pertains to.
* Provide details of any issues with the documentation or improvements you'd like to see below.

The issue is related to the following lines:
```javascript
// Enable SRA to honor competetive exclusions and roadblocks.
googletag.pubads().enableSingleRequest();
```

It says that the line above is enabling SRA. But in the docs, the following is stated regarding SRA:
>This requires all Publisher Ads slots to be defined and added to the PubAdsService prior to enabling the service.
And the demo is showing an infinite layout setup, where new slots get defined every time the user presses the button.

From the docs, it seems that only slots that were defined prior to that call would "honor competitive exclusions and roadblocks.".  Also, there's a typo in the word 'competitive'.

**Comment by jimper** [comment]
Hi @michelangelo246, thanks for the report. This topic is definitely a little confusing.

In general, the only way to **guarantee** that roadblocks and exclusions are honored is to request all your ad slots at once using SRA. However, GPT's [long-lived pageview (LLPV)](https://support.google.com/admanager/answer/183281) keeps track of ads served throughout the entire life of the page, to support roadblocks and exclusions across requests. This LLPV approach works in most cases, but it's not as reliable as batching all of your slots together into a single SRA request (for example, it can fail if multiple ad requests are made in parallel).

So for this code sample where ads are being loaded one-by-one, SRA isn't strictly required. Even without it, roadblocks and exclusions would be honored as long as all the ad requests were properly serialized. However, many actual GPT implementations end up defining/requesting ad slots in batches, so we include it in the sample to demonstrate best practice.

I'll get that typo fixed and look into having the reference docs updated for clarity.

**Comment by michelangelo246** [comment]
Thanks, @jimper. I appreciate the clarification.
