### ISSUE TITLE
Sample feedback: basic/display-anchor-ad

### ISSUE THREAD

**Issue by nwagelmans** [googleads/google-publisher-tag-samples#36]
* If not pre-filled, update the title of this issue with the name of the audit this feedback pertains to.
* Provide details of any issues with the documentation or improvements you'd like to see below.

I am trying to implement anchor ads with Adsense backfill on to my website using Ad Manager, and I have been following the sample implementation as described in the docs, like on this example page: https://googleads.github.io/google-publisher-tag-samples/basic/display-anchor-ad/demo.html

But I am unable to get the anchor ads to display correctly on desktop, both for the top- and bottom anchor ads. Loading an example anchor ad with either `#gamBottomAnchorDemo` or `#gamTopAnchorDemo` in the url does work, so I am confused of what I am doing wrong or why the example page is not working for me.

Thanks in advance for looking into this!

**Comment by jimper** [comment]
Hi @nwagelmans!

It looks like there was a misconfiguration in our Ad Manager test network that was preventing the demo page was loading anchor ads on desktop (basically, there was no line item configured to serve an ad of the [appropriate size](https://support.google.com/admanager/answer/10452255#web-anchor-sizes)). I just made a few tweaks so it should be fixed now. Feel free to reopen this issue if you're still having issues, though.

For help troubleshooting your own integration, I recommend either reaching out on the [Ad Manager community forum](https://support.google.com/admanager/thread/new) or contacting the technical account manager for your Ad Manager account.
