### ISSUE TITLE
shototav

### ISSUE THREAD

**Issue by MDSHEAKHRAFID** [googleads/google-publisher-tag-samples#47]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimper** [comment]
Hello @MDSHEAKHRAFID, if you've encountered a bug, please fill out the issue template when the requested information. Without this information there is nothing we can do to assist.
