### ISSUE TITLE
Sample feedback: display-anchor-ad/js

### ISSUE THREAD

**Issue by mateusnds** [googleads/google-publisher-tag-samples#49]
* If not pre-filled, update the title of this issue with the name of the audit this feedback pertains to.
* Provide details of any issues with the documentation or improvements you'd like to see below.

Hello, I'm trying to place a banner anchor on mobile devices, but the example below doesn't work.

Could you please provide a code sample that doesn't have the static ad and works just to display a banner anchor on mobile?

Thanks

**Comment by jimper** [comment]
Hi @mateusnds, the [test page](https://googleads.github.io/google-publisher-tag-samples/display-anchor-ad/js/demo.html) for this sample seems to be working as expected on both mobile and desktop. Could you provide more details about the specific problem you're having and what troubleshooting steps you've already tried? A jsfiddle or similar that reproduces the issue would be ideal.
