### ISSUE TITLE
Add `allow="payment"` to whitelisted AdSense Attributes

### ISSUE THREAD

**Issue by ryan-lambert-IEX** [googleads/google-publisher-tag-samples#77]
**Is your feature request related to a problem? Please describe.**
As of Safari 17 ([Release Notes](https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes#Apple-Pay)), ApplePay is supported within cross-origin iframes with the `allow="payment"` attribute.

There is no way to add / edit the `allow` parent googletag iframe attribute. Ideally, publishers could enable this feature and add / edit the `allow` attribute to enable ApplePay to work within embedded ads.

**Describe the solution you'd like**
I would like to use the existing `set` API (e.g., `googletag.pubads().set` or similar) to add the `allow="payment"` attribute to the GPT parent iframe. This would require adding this attribute to the whitelsited [AdSense Attributes](https://developers.google.com/publisher-tag/adsense_attributes) or providing some other way to add / edit the `allow` attribute to enable this flag.

**Describe alternatives you've considered**
An alternative would be to allow the `allow="payment"` attribute to be added serverside.

**Additional context**
We are an approved Third-Party Ad partner (see list - [Dispatch - Digital Asset Communication LLC](https://developers.google.com/third-party-ads/adx-vendors?visit_id=638344647362653627-232061200&rd=1)) and our product is shoppable display ads. It would be a large unlock to the ecosystem to optionally enable ApplePay for our ad format.

Please let me know if there is a better place to make this request.

Thank you.

**Comment by jimper** [comment]
Hi @ryan-lambert-IEX, thanks for the feedback! Unfortunately this isn't the right support channel for product feature requests. While I will pass your request along to the team, I won't be able to provide any updates here.

If you have an Ad Manager support contact, I recommend reaching out to them about this as well. They will be best equipped to handle this sort of request and keep you updated as things progress.
