### ISSUE TITLE
Sample feedback: basic-concepts/ts

### ISSUE THREAD

**Issue by yeapesdt** [googleads/google-publisher-tag-samples#83]
* If not pre-filled, update the title of this issue with the name of the audit this feedback pertains to.
* Provide details of any issues with the documentation or improvements you'd like to see below.
There is no example code .

**Comment by jimper** [comment]
Hi @yeapesdt, can you clarify what issue you have with this sample? The generated code can be found in this repo under [dist/basic-concepts](../tree/main/dist/basic-concepts).
