### ISSUE TITLE
Sample feedback: ad-sizes/js

### ISSUE THREAD

**Issue by Noizysam** [googleads/google-publisher-tag-samples#84]
It shows 404 not found

**Comment by jimper** [comment]
Hi @Noizysam, thanks for the report. Are you referring to the "Improve this Sample" button? If so, a fix will be coming for that shortly. If there's some other broken link, please let me know.

**Comment by Noizysam** [comment]
Yes, I was referring to this button. I got it, thanks for the information.

чт, 21 мар. 2024 г. в 13:29, Jon Imperiosi ***@***.***>:

**Comment by jimper** [comment]
This should be fixed now. Thanks again for the report!
