### ISSUE TITLE
Not show rewarded ads

### ISSUE THREAD

**Issue by vtbelo** [googleads/google-publisher-tag-samples#85]
Why when I change ad unit Id and code on my created ad unit no ads showing?

**Comment by jimper** [comment]
Hi @vtbelo, is this [rewarded ad demo page](https://googleads.github.io/google-publisher-tag-samples/display-rewarded-ad/js/demo.html) working for you? Have you tried modifying [the code here](https://developers.google.com/publisher-tag/samples/display-rewarded-ad) to suit your needs, or are you doing something else?

There are many issues that could cause an ad not to show, so without more information (ideally a live demo) there isn't much specific advice I can give. As a first step, you could try checking whether there are any errors or warnings being logged in the [Publisher Console](https://developers.google.com/publisher-tag/guides/publisher-console).

**Comment by vtbelo** [comment]
Hi, Jon!

Yes I've copied code from here:
https://developers.google.com/publisher-tag/samples/display-rewarded-ad.
Here this code in my domain (it's work ok): https://vanuplay.com/test3.html
Here same code but with my ad unit code and id (it's not working):
https://vanuplay.com/test2.html
Here test banner ads in my domain with my ad unit code and id (it's work
ok): https://vanuplay.com/test1.html
For rewarded ads I've create ad unit with this settings:
https://gyazo.com/005ec20c048b8e94c68060a25a0d7efa
This ad unit code and id I use in test2.html:
https://gyazo.com/8911781641445f1ac27ab770174ec5e0
This site (where I testing) vanuplay.com is approved by Adsense:
https://gyazo.com/b93524946ab2703add03cd9237d58c2c and ads.txt uploaded:
https://vanuplay.com/ads.txt
This is my account network settings:
https://gyazo.com/488f84425cccfcb66486c26c351f024c
Account Network code: 23104251798
Account is verified: https://gyazo.com/4d78d062bdee42290456d54e76ddba4f
Please tell me what could be the problem? Why are Rewarded ads not working?

Thank you!

Best regards,
Vitaly Belokobylskiy
Clever Apps Pte Ltd

**Comment by jimper** [comment]
Hi @vtbelo, I don't see any obvious issues with your code. From the publisher console I can see that an ad request is being made, but no ad is returned. This would seem to indicate a misconfiguration on the Ad Manager side, which I'm unfortunately not able to help with.

I suggest reviewing the documentation on [trafficking rewarded ads](https://support.google.com/admanager/answer/9116812). If that doesn't help identify the issue, you can reach out to [Ad Manager support](https://developers.google.com/publisher-tag/support/feedback-questions) for further assistance.

**Comment by vtbelo** [comment]
Hi, Jon!Thank you very much! Try to ask Ad Manger team.Best regards,Vitaly BelokobylskiyOn 1 Apr 2024, at 05:36, Jon Imperiosi ***@***.***> wrote:﻿
Hi @vtbelo, I don't see any obvious issues with your code. From the publisher console I can see that an ad request is being made, but no ad is returned. This would seem to indicate a misconfiguration on the Ad Manager side, which I'm unfortunately not able to help with.
I suggest reviewing the documentation on trafficking rewarded ads. If that doesn't help identify the issue, you can reach out to Ad Manager support for further assistance.
