### ISSUE TITLE
Refresh by time

### ISSUE THREAD

**Issue by mwaqarakram94** [googleads/google-publisher-tag-samples#87]
Hi So the sample here given info about refresh on button click, which is almost never used. 

https://developers.google.com/publisher-tag/samples/refresh

Refresh by time interval is often used so sample should be about that

Thanks

**Comment by jimper** [comment]
Hi @mwaqarakram94, thanks for the feedback. Our samples don't cover every use case, but you're welcome to take the code we provide and modify it to fit your needs. You may also want to review the [Control ad loading and refresh guide](https://developers.google.com/publisher-tag/guides/control-ad-loading#best_practices), which contains a code snippet that extends this sample to refresh based on a timer.
