### ISSUE TITLE
Sample feedback: lazy-loading/js

### ISSUE THREAD

**Issue by ahmaxed** [googleads/google-publisher-tag-samples#92]
* If not pre-filled, update the title of this issue with the name of the audit this feedback pertains to.
* Provide details of any issues with the documentation or improvements you'd like to see below.

the samples are not previewed.

**Comment by jimper** [comment]
Hi @ahmaxed, if you're talking about [this sample](https://developers.google.com/publisher-tag/samples/lazy-loading), the lack of a preview is intentional. As mentioned above the code:

> This sample makes use of library features that are not fully supported when running in an iframe. To view a demo of this sample in a new window, click the View demo button above.

The demo can be accessed at https://googleads.github.io/google-publisher-tag-samples/lazy-loading/js/demo.html
