### ISSUE TITLE
Sample feedback: display-rewarded-ad/js

### ISSUE THREAD

**Issue by williesmithchen** [googleads/google-publisher-tag-samples#93]
There is no sample code, and I can't see any examples. Is this example supposed to be like this?
<img width="1789" alt="截圖 2024-05-16 17 12 23" src="https://github.com/googleads/google-publisher-tag-samples/assets/4962190/433ee41b-392a-44b3-a008-06b8e93b2af1">
<img width="1792" alt="截圖 2024-05-16 17 12 32" src="https://github.com/googleads/google-publisher-tag-samples/assets/4962190/3fc5a1bf-5031-4016-bc03-5097d97873ce">
[https://googleads.github.io/google-publisher-tag-samples/display-rewarded-ad/js/demo.html](https://googleads.github.io/google-publisher-tag-samples/display-rewarded-ad/js/demo.html)

**Comment by jimper** [comment]
Hi @williesmithchen, what browser are you seeing this behavior on? Could you also open your browser's developer tools and let me know if there are any errors or warnings displayed in the console?

My guess is that something on your end is blocking requests to our playground and/or Ad Manager, but I can't say for sure without more info.
