### ISSUE TITLE
Sample feedback: lazy loading Sample

### ISSUE THREAD

**Issue by ahmaxed** [googleads/google-publisher-tag-samples#94]
In the [lazy loading sample](https://googleads.github.io/google-publisher-tag-samples/lazy-loading/js/demo.html) there is confusing script and a comment in the body that displays the first ad.
```      
googletag.cmd.push(function () {
  // Request all previously defined ad slots.
  googletag.display("div-1");
});
```
Although the comment says "request all previously defined ad slots", it only displays the first one.
Is only displaying the first one intentional or should the script display all of the pre-defined slots?

**Comment by jimper** [comment]
Hi @ahmaxed, thanks for reaching out. With lazy loading, requesting an ad (fetch) and displaying an ad (render) are controlled seperately. In this case, the behavior of the sample is explained in an earlier comment:

```
<!--
  As defined by lazy load settings, initially:
  1. Slot 1 will be fetched and rendered on mobile and desktop.
  2. Slot 2 will be fetched on mobile and desktop, but will not be rendered on desktop.
  3. Slot 3 will be fetched on mobile and desktop, but rendered on neither.
-->
```

Basically, the first call to `display()` requests ads for all 3 slots. However, only slots that are "visible" based on the lazy loading config have their ads displayed. The other ad slots are displayed as they're about to be scrolled into view.
