### ISSUE TITLE
Sample feedback: display-limited-ad/js

### ISSUE THREAD

**Issue by patmmccann** [googleads/google-publisher-tag-samples#96]
you spelled gpt wrong in the text above. (at https://developers.google.com/publisher-tag/samples/display-limited-ad)

The console warning coming from calling limited ads mode manually when loading from the regular url is very confusing. 

It seems to suggest we should go load gpt from a different url. Instead, it should mention we are in automatic mode and the api call is unnecessary

![image](https://github.com/googleads/google-publisher-tag-samples/assets/1683175/28ff0adf-2a3b-4e62-8f4a-60ebad1a86f5)

should be corrected to say GPT is operating in automatic mode and the call is unnecessary

**Comment by patmmccann** [comment]
One other note: It seems the route of loading GPT from the alternate domain is no longer useful, as you require tcf. Everyone should be in automatic mode at this point.

**Comment by jimper** [comment]
Hi @patmmccann, thanks for the feedback!

You're right that automatic mode will be enabled for many publishers, in which case it's not necessary to manually enable limited ads via the PrivacySettings API. There are still situations where the API is useful, however, so we're releasing some update to the documentation and messaging to hopefully reduce confusion. It may take a few days for all of these updates to roll out.
